In [3]:
"""
Batches:
1. we can calculate the things in parallel the bigger the batch there will be more parallization. That is
why we also use GPU compaired to CPU. Because GPU have more cores to perform fatser calculations.
2. Helps with generalization. Rather than telling your machine one feature at a time you can now show multiple.
Dont show all of the data because it will cause over fitting.
let batch size be: 32 64 128
"""
import numpy as np

In [19]:
"""
We have to perform transpose as matrix multiplication is important
1x0.2+2.0x0.8+-1.5x-0.5+?x1.0 --> its a shape error so we can solve this by performing transpose (making rows the columns,vise versa)
"""
weights = [[0.2,0.8,-0.5,1.0],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]
"""here as there is only 1 neuron so we wont change or add the weight """
Input = [[1,2,3,2.5],
         [2.0,5.0,-1.0,2.0],
         [-1.5,2.7,3.3,-0.8]]
bias = [2,3,0.5]
##covert the weights to numpy array and transpose
output = np.dot(Input,np.array(weights).T)+bias
print(output)

[[ 2.8   -1.79   1.885]
 [ 6.9   -4.81  -0.3  ]
 [-0.59  -1.949 -0.474]]


In [9]:
"""
creating more layers now
"""
weights = [[0.2,0.8,-0.5,1.0],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

bias = [2,3,0.5]
#layer 2
weights2 = [[0.1,-0.14,-0.5],
           [0.5,0.12,0.33],
           [-0.44,-0.73,-0.13]]

bias2 = [-1,2,-0.5]
output_layer1 = np.dot(Input,np.array(weights).T)+bias ##it will become input for layer 2
output_layer2 = np.dot(output_layer1,np.array(weights2).T)+bias2
print(output_layer2)

[[-1.8819   5.33225 -3.80535]
 [ 0.0434   6.2988  -3.1207 ]
 [-1.01914  2.8397  -1.89101]]


In [26]:
"""
Now objectifying the layers 
"""
#This input will be our actaul data now
X = [[1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]]
"""
now we will define hidden layer.
We will initialize by adding weights randomly.
As a progarmmer we should know the number of input and its features.
we need our weights to be smaller thus maybe like betweeb -1 to 1 -0.1 to 0.1
selecting big number will create bid out put that will not be helpful thus x weight by some small number 
lets say 0.10.
"""
np.random.seed(0)
class layer_Dense:
    def __init__(self,n_input,n_neurons):
        self.weights = 0.10*np.random.randn(n_input,n_neurons)
        self.biases = np.zeros((1,n_neurons))
    """input can be from 2 things from actaul data X or from hidden layer"""
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights)+self.biases
 ## size of input and how many neurons we want
##here we know the number of input that is features =4
layer1 = layer_Dense(4,5)
layer2 = layer_Dense(5,2)
layer1.forward(X)
print("layer1_output: ",layer1.output)
layer2.forward(layer1.output)
print("layer2_output",layer2.output)


layer1_output:  [[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
layer2_output [[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
