In [ ]:
"""
Softmax is for output layer.
the first thing to check the model is to see how wrong it it.
"""

In [3]:
"""
what we will do here is to use exponential function. This is because output can ne in neg too and we have to tackle that
issue
"""
import math
output_layer = [4.8,1.21,3.385]
E =math.e
expo_val = []
for i in output_layer:
    expo_val.append(E**i)
print(expo_val)
    


[121.51041751873483, 3.353484652549023, 29.517992716151483]


In [4]:
"""
Now we will normalize the value
y = [u1/u1+u2
      u2/u1+u2]
this will give us probabilty distribution but we have to do exponential first. to convert neg to pos without giving
up on the values.
norm is done after exponetianl
"""
norm_sum = sum(expo_val)
norm_val = []
for i in expo_val:
    norm_val.append(i/norm_sum)
print(norm_val)


[0.7870768629140863, 0.02172200733119744, 0.1912011297547162]


In [10]:
"""
Every thing using Numpy
"""

import numpy as np
import math
import nnfs
nnfs.init()
output_layer = [4.8,1.21,3.385]
exponential_val = np.exp(output_layer)
norm_value =exponential_val/np.sum(exponential_val)
print(norm_value)



[0.78707686 0.02172201 0.19120113]


In [17]:
"""
Input > exponential > normalize > output
exponential + normalization  = softmax activation
lets make a batch size
"""
nnfs.init()
Output = [[4.8,1.21,3.385],
         [8.9,-1.81,0.2],
         [1.41,1.051,0.026]]
Exponential_val = np.exp(Output)
#axis=1 means row wise sum
Norm_val =Exponential_val/np.sum(Exponential_val, axis=1, keepdims=True)
print(Norm_val)

[[7.87076863e-01 2.17220073e-02 1.91201130e-01]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [23]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()
##we will also use this for our dataset

X = [[1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]]
Input = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
X,y = spiral_data(100,3)
class layer_Dense:
    def __init__(self,n_input,n_neurons):
        self.weights = 0.10*np.random.randn(n_input,n_neurons)
        self.biases = np.zeros((1,n_neurons))
   
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights)+self.biases

class Activation_Relu:
    #it will get input and produce an output
    def forward(self,Input):
        self.output = np.maximum(0,Input)
        
class Softmax_Activation:
    def forward(self,Input):
        ##this way w will not hit the overflow value
        exp_val = np.exp(Input-np.max(Input,axis=1,keepdims=True))
        probabilities  = exp_val/np.sum(exp_val,axis = 1 , keepdims=True)
        self.output = probabilities

layer1 = layer_Dense(2,3)
activation1  = Activation_Relu()
layer2 = layer_Dense(3,3)
activation2  = Softmax_Activation()

layer1.forward(X)
activation1.forward(layer1.output)

layer2.forward(activation1.output)
activation2.forward(layer2.output)
print(activation2.output[:5]) #start 5 val of batch


[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
